[project]
name = "pytsfiler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pycryptodome>=3.21.0",
    "requests>=2.32.3",
]
